title: "工具集"
description: "可扩展的在线工具集合"
url: "https://pengjunlong.github.io"
baseurl: "/tools"
timezone: Asia/Shanghai
lang: zh-CN

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "default"
minimal_mistakes_font_family: "system"

plugins:
  - jekyll-include-cache

repository: ""
teaser: ""

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      sidebar:
        nav: "tools"
  - scope:
      type: "app"
    values:
      layout: "single"
      author_profile: false
      sidebar:
        nav: "tools"

author:
  name: ""

collections:
  app:
    output: true
    permalink: /app/:name/

